# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 07:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('details', models.TextField()),
                ('giturl', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('deployedurl', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
