# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='portifolio',
            name='porttags',
            field=models.ManyToManyField(to='porti.Tag'),
        ),
    ]
