# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porti', '0002_auto_20180222_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='port_image',
            field=models.ImageField(blank=True, null=True, upload_to='portifolio/'),
        ),
    ]
